name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          cd backend/mybackend
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd backend/mybackend
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend/mybackend
          source venv/bin/activate
          python manage.py test

      - name: Collect static files
        run: |
          cd backend/mybackend
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: backend/mybackend

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: |
          cd myapp
          npm install

      - name: Build frontend
        run: |
          cd myapp
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_FRONTEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: myapp/build